#!/bin/bash

DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

echo_separator () {
	echo "=> $1.."
}
run () {
	echo -n "=> $1.."
	eval "${@:2}" && echo "ok" || echo "failed"
	# last status code is returned
}

relink () {
	echo -n " > linking $2 <- $1..."

	if [ -L "$2" ]; then
		# Remove existing symlink
		unlink "$2"
		echo -n "rm..."
	fi
	if [ -f "$2" ]; then
		# Backup existing file
		rm -f "$2.bak"
		mv "$2" "$2.bak"
		echo -n "bak..."
	fi

	ln -s "$1" "$2"
	echo "done"
}

srelink () {
	echo -n " > linking $2 <- $1..."

	if [ -L "$2" ]; then
		# Remove existing symlink
		unlink "$2" 2> /dev/null
		echo -n "ulink..."
	fi
	if [ ! -f "$2" ]; then
		sudo ln -s "$1" "$2"
		echo "done..."
	else
		echo "skipping (already exists)"
	fi
}

run "Asking for user privileges" \
	'$(sudo -v)' || exit $?;

echo_separator "Symlinking files in home directory"
relink "$DIR/zsh/zshrc"      "$HOME/.zshrc"
relink "$DIR/zsh/zshenv"     "$HOME/.zshenv"
relink "$DIR/git/config"     "$HOME/.gitconfig"

echo_separator "Symlinking bin/* into /usr/local/bin"
for FILE in "$DIR"/bin/*; do
	srelink "$FILE" /usr/local/bin/`basename $FILE`
done


# OSX Defaults
# Some imports from https://github.com/mathiasbynens/dotfiles, some of my own

run "Set Safari’s home page" \
	defaults write com.apple.Safari HomePage -string "http://news.ycombinator.com"

run "Allow hitting the Backspace key to go to the previous page in history" \
	defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2BackspaceKeyNavigationEnabled -bool true

run "Make Safari’s search banners default to Contains instead of Starts With" \
	defaults write com.apple.Safari FindOnPageMatchesWordStartsOnly -bool false

run "Use plain text mode for new TextEdit documents" \
	defaults write com.apple.TextEdit RichText -int 0 \&\&\
	defaults write com.apple.TextEdit PlainTextEncoding -int 4 \&\&\
	defaults write com.apple.TextEdit PlainTextEncodingForWrite -int 4

run "Prevent Photos from opening automatically when devices are plugged in" \
	defaults -currentHost write com.apple.ImageCapture disableHotPlug -bool true

run "Disable the sudden motion sensor as it’s not useful for SSDs" \
	sudo pmset -a sms 0

# Setting hibernate mode to 0: don't write RAM do disk (fast sleep)
# Remove the sleep image file to save disk space 
# Create a zero-byte file instead…
# …and make sure it can’t be rewritten
run "Disable hibernation (speeds up entering sleep mode)" \
	sudo pmset -a hibernatemode 0 \&\&\
	sudo rm -f /private/var/vm/sleepimage \&\&\
	sudo touch /private/var/vm/sleepimage \&\&\
	sudo chflags uchg /private/var/vm/sleepimage
